### ISSUE TITLE
LeGo_2_5_1\Resources\Scripts\System\VisualFx\Hero_Hurt.d Missing in Lego2.6

### ISSUE THREAD

**Issue by skydivin4ng3l** [Lehona/LeGo#12]
I was wondering if this still has to be added to Scripts/System/VisualFX/VisualFxInst.d

Since I was trying to port the BloodSplats Ninja Patch to the current Lego Version as an Exercise, I noticed that the file is no longer in the Release and that there are some changes in Bloodsplats.

I am not sure why it is not working as expected, I could imagine it is because this is missing now?

**Comment by szapp** [comment]
Hi Chris,

that file is used for LeGo in Gothic 2 (Gothic 1 does not support the effects used). If the file is not included in the release, that is probably a mistake. Nevertheless, the file is not too important. All it does is add a short, red screen blend when any blood splat is created on the screen. Without it, the blood splats (and their mechanics) should still work without problems.

I wonder what you mean by:
> I was trying to port the BloodSplats Ninja Patch to the current Lego Version

What exactly is there to port?

**Comment by skydivin4ng3l** [comment]
Hi szapp,

It is a preparation project of mine to get used to Modding in G2 my goal is a dynamic HUD which blends in when it is relevant.

Since I want to mod it in the way that it can be added whenever you want, I want to use Ninja.

As a base I use the Bloodsplats Ninja patch which is based on older versions of Lego/Ikarus at least not lego 2.6.

So I currently try to recreate the Bloodsplats Ninja patch but with the current versions of Lego/Ikarus to learn if it will work with 2.6.

But it seams i can not get it to work and therefore I was wondering if it maybe related to the missing file.

Since this seams not the case (I already tried it in the meantime) ;) the mistake seams to be elsewhere, does Ninja maybe not work with wildcard inclusions, like EngineClasses_G2\*.d?

I also left out __BUTTONS_NINJA_BLOODSPLATS.D and __VIEW_NINJA_BLOODSPLATS.D Since did not get if they are actually used an IDE for funtion lookups would be awesome XD

Thank you for your time and help =)

**Comment by szapp** [comment]
Ninja 1.2 is messy to work with. I suggest to wait for Ninja 2.0, which is more intuitive and stable in conjunction with LeGo. Ninja does not allow wild cards in SRC files.

For more support about Ninja, I suggest to move this discussion to the World of Gothic forum ([Ninja thread](https://forum.worldofplayers.de/forum/threads/1515286)).
