### ISSUE TITLE
Add safety checks for loading functions

### ISSUE THREAD

**Issue by szapp** [Lehona/LeGo#21]
The functions `PM_LoadFuncID`, `PM_LoadFuncOffset` and `PM_LoadFuncPtr` should somehow catch non-existing functions. At the moment, loading handles containing non-existing functions results in a crash.

Simply returning something like `-1` might not be sufficient, because the functions are called from different contexts. More specifically, they are called from archiver functions of classes. This may be the case for user-created classes as well outside of LeGo, which cannot be changed at this point.

So instead, the problem should be handled within these functions and I propose to simply return (the ID/offset/ptr of) an empty function, i.e.
```D
func void PM_empty_func() {};

// ... 

func int PM_LoadFuncID(var string name) {
    var int id; id = MEM_FindParserSymbol(PM_LoadString(name));
    if (id == -1) {
        id = MEM_GetFuncID(PM_empty_func); // Or similar
    };
    return id;
};
```

I am not sure about the repercussions, though. Will this break any packages (Buffs, Buttons, ...)?

**Comment by Lehona** [comment]
No LeGo package relies on user-supplied function doing something, as far as I can remember they might as well be empty functions (+/- keeping the stack intact).

Classes that have optional user-supplied functions (i.e. where it might make sense to differentiate between empty user-supplied functions and no user-supplied functions) only save a funcID iff the ID is valid, iirc.

Looks good to me.

**Comment by szapp** [comment]
The comment about keeping the stack intact was good. The expected function signature varies quite a bit. I would suggest to check the loaded function afterwards in the unarchiver functions of the classes and if they are found to be equal to `PM_empty_func`, replace them by analogous ones with valid signatures if necessary. These are the expected signatures.


Class        | Class variable | Expected signature
------------ | -------------- | -----------------------------
A8Head       | fnc            | void fnc(int) or void fnc(int, int)
&nbsp;       | dfnc           | void fnc()
lCBuff       | OnApply        | void fnc(int)
&nbsp;       | OnTick         | void fnc(int)
&nbsp;       | OnRemoved      | void fnc(int)
_Button      | on_enter       | void fnc(int)
&nbsp;       | on_leave       | void fnc(int)
&nbsp;       | on_click       | void fnc(int)
lCEvent      |                | void fnc(int)
callbackData | funcID         | void fnc() or void fnc(int)
FFItem       | fncID          | void fnc() or void fnc(int)

**Comment by szapp** [comment]
I created a separate branch for this issue, see #24
