### ISSUE TITLE
Bar_SetAlpha missing alphafunc ?

### ISSUE THREAD

**Issue by Fawkes-dev** [Lehona/LeGo#26]
I tested `Bar_SetAlpha` and noticed only backText was transparent, while barTex was fully visible - shouldn't both view change their alphaFunc to ALPHA_FUNC_ADD? (also an idea - would it make sense to have option to adjust alpha values for both views?)
```c++
func void Bar_SetAlpha(var int bar, var int alpha) {
	if(!Hlp_IsValidHandle(bar)) { return; };
	var _bar b; b = get(bar);
	var zCView v; v = View_Get(b.v0);
	v.alpha = alpha;
	if((v.alpha != 255) && (v.alphafunc == 1)) {
		v.alphafunc = 2;
	};
	v = View_Get(b.v1);
	v.alpha = alpha;
	if((v.alpha != 255) && (v.alphafunc == 1)) {
		v.alphafunc = 2;
	};
};
```

**Comment by szapp** [comment]
Good catch. It may be easier to just call the respective function from LeGo_Views for both views.

As for the idea, to handle it separately for both views, I think that would be very unusual for bars. If someone wants to do that, they can just refer to the individual views themselves.
