### ISSUE TITLE
Improve `Talents.Npc_FindByID` to stop on first occurence of ID

### ISSUE THREAD

**Issue by kirides** [Lehona/LeGo#31]
Currently `Npc_FindByID` looks at every single NPC to find a specific talent id, even if the found id (which should be _unique_) is found after just a few iterations.

I propose we alter the code for `Npc_FindByID` to stop iterating as soon as we found the first matching NPC with said ID.

![grafik](https://user-images.githubusercontent.com/13602143/123415180-2adf3480-d5b5-11eb-970a-5a7d236f288c.png)

Before the change, every single buff that would use `Buff_GetNpc` would look at > 700 NPCs, even though just 10-15 iterations (optimally) were enough.

That, combined with having skills that target multiple NPCs (e.g. Firerain proccing many buffs, each summoned creature having a buff) could previously lead to significant stutter.

In a test on my machine, this code improved the performance for 24 summons (3x army of darkness, all summoned creatures having a buff that uses `Buff_GetNpc`) from 40-45 FPS and stuttering every 1000ms, to 55-60 fps and no stuttering.

**Comment by Lehona** [comment]
That's an embarrassing oversight by me, would you be so kind and create a PR? :)

**Comment by kirides** [comment]
Sure, would you want the proposed change, or remove the function calls alltogether and combine it all into one?
