### ISSUE TITLE
Multiple Buff_Has - checks with operator || do not work

### ISSUE THREAD

**Issue by Atariar** [Lehona/LeGo#34]
Hello everyone,

Regarding Buff_Has I've experienced a issue checking if a npc has multiple buffs.

My aim is to identify if a npc has beend executed while being burned by a fire spell.
Multiple Buff_Has with operator || doesn't work for me. See:
`
// I. E. condition in ZS_Dead
if (Buff_Has(slf, burn_firebolt_exp))
|| (Buff_Has(slf, burn_firebolt))
|| (Buff_Has(slf, burn_fireball_exp))
|| (Buff_Has(slf, burn_fireball))
|| (Buff_Has(slf, burn_firestorm_exp))
|| (Buff_Has(slf, burn_firestorm)) 
|| (Buff_Has(slf, burn_firerain_exp))
|| (Buff_Has(slf, burn_firerain)) 
|| (Buff_Has(slf, burn_firearrow_exp))
|| (Buff_Has(slf, burn_firearrow))
|| (Buff_Has(slf, burn_fire_exp)) {
  PrintS("Test");
  //Nothing happens
};
`

For the exact same situation, only asking for the correct Buff without || works fine
`
if Buff_Has(slf, burn_fireball_exp) {
  PrintS("Test");
  //This works for the exact same situation.
};
`

**My setup is:**

- Ikarus 1.22
- LeGo 2.8

What do you think?

**Comment by Lehona** [comment]
Can you try changing https://github.com/Lehona/LeGo/blob/dev/Buffs.d#L254 to `return +Buff_BuffHndl;` (I added a plus)? This should fix that behaviour.

**Comment by Atariar** [comment]
@Lehona Thanks alot! It resolved the issue. :)

**Comment by Lehona** [comment]
Thanks for reporting :)
