### ISSUE TITLE
Buffs: Hide active buffs on hero during dialogs etc.

### ISSUE THREAD

**Issue by Lehona** [Lehona/LeGo#5]
Bloodfly91: 

> Mir ist noch etwas bei den Buffs aufgefallen. Sämtliche Buff-Texturen aktiver Buffs des Helden werden auch weiterhin angezeigt, wenn das Spiel pausiert ist oder wenn der Spieler sich in einem Dialog befindet. Da beim pausieren des Spiels und in Dialogen das HUD ausgeblendet wird, sollten mMn. auch die Buffs dann nicht mehr sichtbar sein.

We will either need a hook in the appropriate location or check this during the FF that runs anyway for the buffs.

**Comment by szapp** [comment]
That location would be `oCGame::ShowPlayerStatus` (not sure about the name), but the property `ogame->showPlayerStatus` can just be checked inside the already present FF.

**Comment by Lehona** [comment]
Implemented in 059ead0e5c69b16f9710858938898b72bc646661.
