### ISSUE TITLE
Add Gothic 1 addresses to Misc.d

### ISSUE THREAD

**Issue by Lehona** [Lehona/LeGo#8]
The Misc.d currently only contains G2 addresses. I do not have gothic 1 installed, so it would be great if someone could add them. There are only 3 addresses needed: atan2, sin and acos.

**Comment by szapp** [comment]
Sorry, I hadn't read the messages on gitter. Maybe @CarnageMarkus gets around to it first, so I'll remove myself from being assigned to this issue.

**Comment by Lehona** [comment]
Fixed in c117976.
